name: zutis Tests
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  Run Tests:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v5
      - uses: https://codeberg.org/mlugg/setup-zig@v2
      - run: zig build test --summary all
